import { FC } from 'react'
import Head from 'next/head'

type TPageHead = {
  [otherProps: string]: any
}

const PageHead:FC<TPageHead> = ({
  ...prpps
}) => {
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default PageHead